<a href="https://colab.research.google.com/github/shivrajanand/PyTorch-Learn/blob/main/PyTorch_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import torch
import numpy as np

**Lecture 2:Tensors**

In [21]:
my_list = [1, 2, 3, 4, 5] #Python list
print(my_list)

[1, 2, 3, 4, 5]


In [22]:
np1 = np.random.rand(3,4) #Numpy array
np1, np1.dtype

(array([[0.24260192, 0.47109155, 0.96593783, 0.04773928],
        [0.70401149, 0.87334334, 0.40840152, 0.50910894],
        [0.98983317, 0.58315214, 0.77836803, 0.081877  ]]),
 dtype('float64'))

In [23]:
tensor_2d = torch.randn(3, 4)
tensor_2d, tensor_2d.dtype

(tensor([[ 0.8797,  0.8246,  0.6396, -1.2343],
         [-0.1853, -1.7168,  1.6336,  0.7785],
         [-0.6040, -0.2269, -0.8312, -0.0718]]),
 torch.float32)

In [24]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d, tensor_3d.dtype

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 torch.float32)

In [25]:
my_t1 = torch.tensor(np1)
my_t1, my_t1.dtype

(tensor([[0.2426, 0.4711, 0.9659, 0.0477],
         [0.7040, 0.8733, 0.4084, 0.5091],
         [0.9898, 0.5832, 0.7784, 0.0819]], dtype=torch.float64),
 torch.float64)

**Lecture 3: Tensor Operations**

In [26]:
myten1 = torch.arange(10)
myten1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
#Reshape and View
myten1 = myten1.reshape(2,5)
myten1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [28]:
#How to reshape if we dont know number of items
myten2 = torch.arange(10)
myten2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
myten2 = myten2.reshape(2,-1)
myten2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [30]:
myten3 = torch.arange(10)
myten3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
myten4 = myten3.view(2,5)
myten4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])